### ISSUE TITLE
Error  from bs4 import BeautifulSoup

### ISSUE THREAD

**Issue by Laddyacris** [bbouko/Recalbox-scraper#5]
Bonjour babou
j'ai copié collé ton code py dans un fichier nommé scrap.py que j ai placé dans le dossier des roms
j ai executé la commande donnée et j'obtiens cette erreur.

 python /recalbox/share/roms/scrap.py
Traceback (most recent call last):
  File "/recalbox/share/roms/scrap.py", line 3, in <module>
    from bs4 import BeautifulSoup
ImportError: No module named bs4

Quelle est mon erreur ?
Acris

**Comment by bbouko** [comment]
il manque le package python-bs4 dans cette version de Recalbox, il devrait être présent dans la 3.3.0.
En attendant tu peux utiliser sur une machine linux et l'installer toi même
